tls:
  certificates:
    - certFile: /etc/certs/local-cert.pem
      keyFile: /etc/certs/local-key.pem

http:
  routers:
    gateway:
      rule: "PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)"
      service: gateway
      entryPoints:
        - websecure
      tls: {}

    jaeger:
      rule: "Host(`jaeger.localhost`)"
      service: jaeger
      entryPoints:
        - websecure
      tls: {}

    prometheus:
      rule: "Host(`prometheus.localhost`)"
      service: prometheus
      entryPoints:
        - websecure
      tls: {}

    grafana:
      rule: "Host(`grafana.localhost`)"
      service: grafana
      entryPoints:
        - websecure
      tls: {}

  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://gateway:8001"
    jaeger:
      loadBalancer:
        servers:
          - url: "http://jaeger:16686"
    prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
