name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
      - main

env:
  REGISTRY: ghcr.io
  # Converts 'owner/repo' structure from github to lowercase as Docker requires
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    name: Build & Publish to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Gateway
        id: meta-gateway
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gateway
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build and push Gateway image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: gateway/Dockerfile
          push: true
          tags: ${{ steps.meta-gateway.outputs.tags }}
          labels: ${{ steps.meta-gateway.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for Worker
        id: meta-worker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-worker
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: processing/Dockerfile
          push: true
          tags: ${{ steps.meta-worker.outputs.tags }}
          labels: ${{ steps.meta-worker.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
